import MovieList from "./MoviesList";

const MOVIE_DATA = {
  page: 1,
  results: [
    {
      adult: false,
      backdrop_path: "/iHSwvRVsRyxpX7FE7GbviaDvgGZ.jpg",
      genre_ids: [10765, 9648, 35],
      id: 119051,
      origin_country: ["US"],
      original_language: "en",
      original_name: "Wednesday",
      overview:
        "Smart, sarcastic and a little dead inside, Wednesday Addams investigates twisted mysteries while making new friends — and foes — at Nevermore Academy.",
      popularity: 279.6872,
      poster_path: "/36xXlhEpQqVVPuiZhfoQuaY4OlA.jpg",
      first_air_date: "2022-11-23",
      name: "Wednesday",
      vote_average: 8.391,
      vote_count: 9799,
    },
    {
      adult: false,
      backdrop_path: "/jCcSS9iDpKgll8Kpp7qVhSn0l1f.jpg",
      genre_ids: [18],
      id: 194766,
      origin_country: ["US"],
      original_language: "en",
      original_name: "The Summer I Turned Pretty",
      overview:
        "Every summer, Belly and her family head to the Fishers’ beach house in Cousins. Every summer is the same ... until Belly turns sixteen. Relationships will be tested, painful truths will be revealed, and Belly will be forever changed. It’s a summer of first love, first heartbreak and growing up — it's the summer she turns pretty.",
      popularity: 241.1343,
      poster_path: "/xBIz53wYWsKfFpN0TaizVAjKJ0z.jpg",
      first_air_date: "2022-06-16",
      name: "The Summer I Turned Pretty",
      vote_average: 8.168,
      vote_count: 961,
    },
    {
      adult: false,
      backdrop_path: "/tW80eVy19UxCp9WZrmLiztdthSE.jpg",
      genre_ids: [35, 10759],
      id: 247043,
      origin_country: ["IN"],
      original_language: "hi",
      original_name: "The Ba***ds of Bollywood",
      overview:
        "In this high-stakes drama, an ambitious outsider and his friends navigate the chaotic, larger-than-life, yet uncertain world of Bollywood.",
      popularity: 219.588,
      poster_path: "/yOXUBEAHPihOcS54A3JmDQICtEr.jpg",
      first_air_date: "2025-09-18",
      name: "The Ba***ds of Bollywood",
      vote_average: 7.5,
      vote_count: 11,
    },
    {
      adult: false,
      backdrop_path: "/biIBy2LPOOtGCgUYOls3dUEWU3v.jpg",
      genre_ids: [10765, 18],
      id: 157239,
      origin_country: ["US"],
      original_language: "en",
      original_name: "Alien: Earth",
      overview:
        "When the mysterious deep space research vessel USCSS Maginot crash-lands on Earth, Wendy and a ragtag group of tactical soldiers make a fateful discovery that puts them face-to-face with the planet's greatest threat.",
      popularity: 202.2868,
      poster_path: "/yueXS3q8BtoWekcHOATFHicLl3e.jpg",
      first_air_date: "2025-08-12",
      name: "Alien: Earth",
      vote_average: 7.682,
      vote_count: 444,
    },
    {
      adult: false,
      backdrop_path: "/aSGSxGMTP893DPMCvMl9AdnEICE.jpg",
      genre_ids: [80, 18, 9648],
      id: 1405,
      origin_country: ["US"],
      original_language: "en",
      original_name: "Dexter",
      overview:
        "Dexter Morgan, a blood spatter pattern analyst for the Miami Metro Police also leads a secret life as a serial killer, hunting down criminals who have slipped through the cracks of justice.",
      popularity: 177.7809,
      poster_path: "/q8dWfc4JwQuv3HayIZeO84jAXED.jpg",
      first_air_date: "2006-10-01",
      name: "Dexter",
      vote_average: 8.2,
      vote_count: 4905,
    },
    {
      adult: false,
      backdrop_path: "/oRdc2nn7jLOYy4fBdvmFKPsKzZE.jpg",
      genre_ids: [80, 18, 9648],
      id: 2734,
      origin_country: ["US"],
      original_language: "en",
      original_name: "Law & Order: Special Victims Unit",
      overview:
        "In the criminal justice system, sexually-based offenses are considered especially heinous. In New York City, the dedicated detectives who investigate these vicious felonies are members of an elite squad known as the Special Victims Unit. These are their stories.",
      popularity: 165.6029,
      poster_path: "/34O6znqnLHAa19mZrQB0sxTDGzH.jpg",
      first_air_date: "1999-09-20",
      name: "Law & Order: Special Victims Unit",
      vote_average: 7.936,
      vote_count: 4012,
    },
    {
      adult: false,
      backdrop_path: "/2m1Mu0xPj4SikiqkaolTRUcNtWH.jpg",
      genre_ids: [80, 18, 35],
      id: 79744,
      origin_country: ["US"],
      original_language: "en",
      original_name: "The Rookie",
      overview:
        "Starting over isn't easy, especially for small-town guy John Nolan who, after a life-altering incident, is pursuing his dream of being an LAPD officer. As the force's oldest rookie, he’s met with skepticism from some higher-ups who see him as just a walking midlife crisis.",
      popularity: 164.3174,
      poster_path: "/bL1mwXDnH5fCxqc4S2n40hoVyoe.jpg",
      first_air_date: "2018-10-16",
      name: "The Rookie",
      vote_average: 8.528,
      vote_count: 2684,
    },
    {
      adult: false,
      backdrop_path: "/fgvM6m7gAd8kDAaLF16aflbOSAK.jpg",
      genre_ids: [18],
      id: 1416,
      origin_country: ["US"],
      original_language: "en",
      original_name: "Grey's Anatomy",
      overview:
        "Follows the personal and professional lives of a group of doctors at Seattle’s Grey Sloan Memorial Hospital.",
      popularity: 146.1542,
      poster_path: "/7jEVqXC14bhfAzSPgr896dMdDv6.jpg",
      first_air_date: "2005-03-27",
      name: "Grey's Anatomy",
      vote_average: 8.2,
      vote_count: 10639,
    },
    {
      adult: false,
      backdrop_path: "/4uWvmON2pqDJtpPAsHMggdDFFrn.jpg",
      genre_ids: [80, 18],
      id: 549,
      origin_country: ["US"],
      original_language: "en",
      original_name: "Law & Order",
      overview:
        "In cases ripped from the headlines, police investigate serious and often deadly crimes, weighing the evidence and questioning the suspects until someone is taken into custody. The district attorney's office then builds a case to convict the perpetrator by proving the person guilty beyond a reasonable doubt. Working together, these expert teams navigate all sides of the complex criminal justice system to make New York a safer place.",
      popularity: 131.7417,
      poster_path: "/6vFL8S6Cci8s7SHWXz60xOisGBC.jpg",
      first_air_date: "1990-09-13",
      name: "Law & Order",
      vote_average: 7.398,
      vote_count: 632,
    },
    {
      adult: false,
      backdrop_path: "/ScaVfT5IkwVC3Edhmxqyl0GbK0.jpg",
      genre_ids: [10759, 18, 10765],
      id: 205715,
      origin_country: ["US"],
      original_language: "en",
      original_name: "Gen V",
      overview:
        "At America's only college for superheroes, gifted students put their moral boundaries to the test, competing for the university's top ranking, and a chance to join The Seven, Vought International's elite superhero team. When the school's dark secrets come to light, they must decide what kind of heroes they want to become.",
      popularity: 129.2496,
      poster_path: "/tEv842Nd5uMSavURG4aQO1pNtst.jpg",
      first_air_date: "2023-09-28",
      name: "Gen V",
      vote_average: 7.719,
      vote_count: 1120,
    },
    {
      adult: false,
      backdrop_path: "/pj1wFbZF3gpEg7F0EreXTvZNZTG.jpg",
      genre_ids: [10759, 10765, 18],
      id: 110492,
      origin_country: ["US"],
      original_language: "en",
      original_name: "Peacemaker",
      overview:
        "The continuing story of Peacemaker, a vainglorious superhero/supervillain who believes in peace at any cost — no matter how many people he has to kill. After a miraculous recovery from his duel with Bloodsport, Peacemaker soon discovers that his freedom comes at a price.",
      popularity: 127.1249,
      poster_path: "/yb4F1Oocq8GfQt6iIuAgYEBokhG.jpg",
      first_air_date: "2022-01-13",
      name: "Peacemaker",
      vote_average: 8.243,
      vote_count: 2979,
    },
    {
      adult: false,
      backdrop_path: "/lirPqYLTtd6XZqGn4cS1wiesTq0.jpg",
      genre_ids: [18, 9648, 10765],
      id: 1622,
      origin_country: ["US"],
      original_language: "en",
      original_name: "Supernatural",
      overview:
        "When they were boys, Sam and Dean Winchester lost their mother to a mysterious and demonic supernatural force. Subsequently, their father raised them to be soldiers. He taught them about the paranormal evil that lives in the dark corners and on the back roads of America ... and he taught them how to kill it. Now, the Winchester brothers crisscross the country in their '67 Chevy Impala, battling every kind of supernatural threat they encounter along the way. ",
      popularity: 125.4441,
      poster_path: "/KoYWXbnYuS3b0GyQPkbuexlVK9.jpg",
      first_air_date: "2005-09-13",
      name: "Supernatural",
      vote_average: 8.301,
      vote_count: 7993,
    },
    {
      adult: false,
      backdrop_path: "/zjOj2gnDJYFdYt6R7FtuHn7yrPr.jpg",
      genre_ids: [18, 35],
      id: 34307,
      origin_country: ["US"],
      original_language: "en",
      original_name: "Shameless",
      overview:
        "Chicagoan Frank Gallagher is the proud single dad of six smart, industrious, independent kids, who without him would be... perhaps better off. When Frank's not at the bar spending what little money they have, he's passed out on the floor. But the kids have found ways to grow up in spite of him. They may not be like any family you know, but they make no apologies for being exactly who they are.",
      popularity: 120.9512,
      poster_path: "/9akij7PqZ1g6zl42DQQTtL9CTSb.jpg",
      first_air_date: "2011-01-09",
      name: "Shameless",
      vote_average: 8.161,
      vote_count: 3007,
    },
    {
      adult: false,
      backdrop_path: "/2OMB0ynKlyIenMJWI2Dy9IWT4c.jpg",
      genre_ids: [10765, 18, 10759],
      id: 1399,
      origin_country: ["US"],
      original_language: "en",
      original_name: "Game of Thrones",
      overview:
        "Seven noble families fight for control of the mythical land of Westeros. Friction between the houses leads to full-scale war. All while a very ancient evil awakens in the farthest north. Amidst the war, a neglected military order of misfits, the Night's Watch, is all that stands between the realms of men and icy horrors beyond.",
      popularity: 119.8625,
      poster_path: "/1XS1oqL89opfnbLl8WnZY1O1uJx.jpg",
      first_air_date: "2011-04-17",
      name: "Game of Thrones",
      vote_average: 8.458,
      vote_count: 25535,
    },
    {
      adult: false,
      backdrop_path: "/c1aBrG5s5xFa6Tbnihu2Hhj4t2q.jpg",
      genre_ids: [80, 18, 10759],
      id: 4614,
      origin_country: ["US"],
      original_language: "en",
      original_name: "NCIS",
      overview:
        "From murder and espionage to terrorism and stolen submarines, a team of special agents investigates any crime that has a shred of evidence connected to Navy and Marine Corps personnel, regardless of rank or position.",
      popularity: 119.4753,
      poster_path: "/mBcu8d6x6zB1el3MPNl7cZQEQ31.jpg",
      first_air_date: "2003-09-23",
      name: "NCIS",
      vote_average: 7.631,
      vote_count: 2392,
    },
    {
      adult: false,
      backdrop_path: "/tsRy63Mu5cu8etL1X7ZLyf7UP1M.jpg",
      genre_ids: [18, 80],
      id: 1396,
      origin_country: ["US"],
      original_language: "en",
      original_name: "Breaking Bad",
      overview:
        "Walter White, a New Mexico chemistry teacher, is diagnosed with Stage III cancer and given a prognosis of only two years left to live. He becomes filled with a sense of fearlessness and an unrelenting desire to secure his family's financial future at any cost as he enters the dangerous world of drugs and crime.",
      popularity: 112.7557,
      poster_path: "/ztkUQFLlC19CCMYHW9o1zWhJRNq.jpg",
      first_air_date: "2008-01-20",
      name: "Breaking Bad",
      vote_average: 8.92,
      vote_count: 16111,
    },
    {
      adult: false,
      backdrop_path: "/yQw23xxmVBFVHPCF6V68TAIIfno.jpg",
      genre_ids: [10759, 18],
      id: 219760,
      origin_country: ["US"],
      original_language: "en",
      original_name: "The Terminal List: Dark Wolf",
      overview:
        "Before The Terminal List, Navy SEAL Ben Edwards finds himself entangled in the black operations side of the CIA. The deeper Ben goes into the 'gray', the harder it will become to not give himself over to his darker impulses. Every man has two wolves inside him – light and dark – fighting for control. Which wolf will Ben Edwards feed?",
      popularity: 112.3196,
      poster_path: "/9mYeRoWguq5etbwJRdF8BXFKiF.jpg",
      first_air_date: "2025-08-27",
      name: "The Terminal List: Dark Wolf",
      vote_average: 7.8,
      vote_count: 72,
    },
    {
      adult: false,
      backdrop_path: "/l7rLHTBhCJ0Ub7ctAh9Vesx6ACK.jpg",
      genre_ids: [18, 80],
      id: 249039,
      origin_country: ["GB", "US"],
      original_language: "en",
      original_name: "Black Rabbit",
      overview:
        "A rising-star restaurateur is forced into New York's criminal underworld when his chaotic brother returns to town with loan sharks on his trail.",
      popularity: 111.2258,
      poster_path: "/4e9CraVtGY00jLP2YGwsuEtaIjR.jpg",
      first_air_date: "2025-09-18",
      name: "Black Rabbit",
      vote_average: 6.737,
      vote_count: 20,
    },
    {
      adult: false,
      backdrop_path: "/7w165QdHmJuTHSQwEyJDBDpuDT7.jpg",
      genre_ids: [10759, 80, 18],
      id: 2288,
      origin_country: ["US"],
      original_language: "en",
      original_name: "Prison Break",
      overview:
        "Due to a political conspiracy, an innocent man is sent to death row and his only hope is his brother, who makes it his mission to deliberately get himself sent to the same prison in order to break the both of them out, from the inside out.",
      popularity: 107.4322,
      poster_path: "/z885tJn5kkUHppjIK1g2Q54iTff.jpg",
      first_air_date: "2005-08-29",
      name: "Prison Break",
      vote_average: 8.1,
      vote_count: 5586,
    },
    {
      adult: false,
      backdrop_path: "/w88B4ooZ2LSYPw5107JOkjvI8PI.jpg",
      genre_ids: [80, 18, 9648],
      id: 4057,
      origin_country: ["US"],
      original_language: "en",
      original_name: "Criminal Minds",
      overview:
        "An elite team of FBI profilers analyze the country's most twisted criminal minds, anticipating their next moves before they strike again. The Behavioral Analysis Unit's most experienced agent is David Rossi, a founding member of the BAU who returns to help the team solve new cases.",
      popularity: 100.47,
      poster_path: "/k6LX0rJOYeF4fNzfVlCGxWPTmE5.jpg",
      first_air_date: "2005-09-22",
      name: "Criminal Minds",
      vote_average: 8.3,
      vote_count: 3921,
    },
  ],
  total_pages: 10257,
  total_results: 205134,
};

const TrendingNow = () => {
  return (
    <div className="px-6 mt-6">
      <h3>Trending Now</h3>

      {MOVIE_DATA?.results?.length > 0 ? (
        <MovieList movies={MOVIE_DATA.results} />
      ) : (
        <div> No movies were found </div>
      )}
    </div>
  );
};

export default TrendingNow;
